package com.tingting.notifier.database.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.tingting.notifier.data.model.TransactionModel

/**
 * Room row for a stored money-movement event. Mirrors [TransactionModel] but adds
 * an autogenerated [id] primary key.
 */
@Entity(tableName = "transactions")
data class TransactionEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val appId: String,
    val bankName: String,
    val amount: Long,
    val isIncome: Boolean,
    val rawText: String,
    val timestamp: Long,
)

/** Domain model → entity (id defaults to 0 so Room autogenerates it on insert). */
fun TransactionModel.toEntity(): TransactionEntity = TransactionEntity(
    appId = appId,
    bankName = bankName,
    amount = amount,
    isIncome = isIncome,
    rawText = rawText,
    timestamp = timestamp,
)

/** Entity → domain model (drops the database id). */
fun TransactionEntity.toModel(): TransactionModel = TransactionModel(
    appId = appId,
    bankName = bankName,
    amount = amount,
    isIncome = isIncome,
    rawText = rawText,
    timestamp = timestamp,
)
