package com.loaloaloa.database.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.loaloaloa.data.model.TransactionModel
import com.loaloaloa.data.model.TransactionRecord

/**
 * Room row for a stored money-movement event. Mirrors [TransactionModel] but adds
 * an autogenerated [id] primary key.
 */
@Entity(tableName = "transactions")
data class TransactionEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val appId: String,
    val bankName: String,
    val amount: Long,
    val isIncome: Boolean,
    val rawText: String,
    val timestamp: Long,
    /** Optional shop-owner annotation; empty by default. Added in DB v2. */
    val note: String = "",
)

/** Domain model → entity (id defaults to 0 so Room autogenerates it on insert). */
fun TransactionModel.toEntity(note: String = ""): TransactionEntity = TransactionEntity(
    appId = appId,
    bankName = bankName,
    amount = amount,
    isIncome = isIncome,
    rawText = rawText,
    timestamp = timestamp,
    note = note,
)

/** Entity → domain model (drops the database id). */
fun TransactionEntity.toModel(): TransactionModel = TransactionModel(
    appId = appId,
    bankName = bankName,
    amount = amount,
    isIncome = isIncome,
    rawText = rawText,
    timestamp = timestamp,
)

/** Entity → id-carrying record (for UI rows that delete/undo by row id, + note). */
fun TransactionEntity.toRecord(): TransactionRecord = TransactionRecord(
    id = id,
    transaction = toModel(),
    note = note,
)
